### ISSUE TITLE
Enhancement: Token as session or header 

### ISSUE THREAD

**Issue by pabloariasmora** [squidfunk/terraform-aws-cognito-auth#1014]
First of all great work! I was able to understand the more about Cognito flow by running this module. Thanks!    

## Description

Not sure if is possible but it will be a nice feature. Flag to set the Identity Token not to be send as part of the url params. Instead use a session cookie or as a header token maybe? This will allow to implement this module and communicate with an application hosted APP_ORIGIN as it should be on a prod environment for example.

By prod example I'm saying that it's advisable to avoid sending them in the URL as stated RFC 6750:

```
Don't pass bearer tokens in page URLs: Bearer tokens SHOULD NOT be passed in page URLs (for example, as query string parameters).

Instead, bearer tokens SHOULD be passed in HTTP message headers or message bodies for which confidentiality measures are taken.

Browsers, web servers, and other software may not adequately secure URLs in the browser history, web server logs, and other data structures. If bearer tokens are passed in page URLs, attackers might be able to steal them from the history data, logs, or other unsecured locations.
```

### Expected behavior
Use a session cookie for the params. As far as I understood this is the file where the redirection to app_domain happens modules/web/app/src/enhancers/with-callback.ts

### Actual behavior
<img width="756" alt="example" src="https://user-images.githubusercontent.com/7321937/72859884-e1393e80-3c8a-11ea-8128-3e0998d33118.png">

Love to help to do it, I'm not really familiar with FrontEnd but I can give it a try. Can you let me know more about the Framework been used for the FrontEnd?

**Comment by squidfunk** [comment]
Yeah, Cognito is quite hard to wrap one's head around in the beginning. Been there.

Let me try to explain why the token handling is implemented as it is. The frontend you're seeing (which is written in React) is just one part of the authentication solution. The other part is a set of Lambda functions that encapsulate Cognito's API and expose it on your domain (as opposed to the hosted UI which will be hosted under some domain specific to Cognito).

Let's zoom in on the authentication endpoint. If you deploy the frontend on `login.myapp.com` and login with `username` and `password` and check the __Remember me__ checkbox, the React app will make the following request

```
curl -XPOST https://login.myapp.com/identity/authenticate -d '{
  "username": "...",
  "password": "...",
  "remember": true
}'
```

If successful, it will send back the __id token__, __access token__ and __refresh token__ as part of the JSON response:

``` json
{
  "id": {
    "token": "...",
    "expires": "2020-..."
  },
  "access": {
    "token": "...",
    "expires": "2020-..."
  },
  "refresh": {
    "token": "...",
    "expires": "2020-..."
  }
}
```

All three tokens are always sent back in the body to enable programatic use. This means you can also use a CLI client to obtain this set of tokens, store away the refresh token and use it to renew your session after the id and access tokens expired (after one hour, set by Cognito).

However, for security reasons, web applications should never save the refresh token inside local storage or in the application state. For this reason, the Lambda endpoint will also send a secure HTTPS-only cookie which can not be read through JavaScript and is thus secure from any attempt to read it by third-party JavaScript. The refresh token from the cookie will automatically be sent when your browser requests the frontend and even before the login form is shown. This is also the reason why the React application immediately discards the refresh token from the body.

So now, we have the refresh token stored in a save place unobservable to third-party JavaScript, and thus only local to the machine you're logging in from.

> Side note: explicitly logging out will also reset the refresh token. This is crucial for when you accidentally checked the __Remember me__ checkbox but realize afterwards that you're using a public computer. You log out and the token is gone, so you're safe.

The whole login logic is hosted on an extra domain, so we have the problem to pass the __id token__ or __access token__ to the application which we're logging in for. You correctly noticed that this is currently done via the URL, however not via query parameter but via __hash fragment__. Hash fragments are (usually) not stored in log files, so there is (i.e. should be) no observable trace. Furthermore everything is encrypted with SSL (your application definitely should!), so the URL is not observable to anyone. Upon initialization, your application should check the URL for the respective hash fragment, decode it and store the token in its state (better not in local storage for the reasons stated). The token is now ready for use, until it expires and your applications backend should respond with a `401` status, which means you redirect the user back to the login form.

Still don't like the hash fragment approach? You're free to pass the token in another way, sure. However, it would mean that after a successful login you would have to store the access token in local storage on the login frontend and request it via and `iframe` and `postMessage` through your application, which you definitely shouldn't (remember: no credentials in local storage), or you could use a `POST` request with a server-side `301` within your application to send the token via `POST` to the server which will store it in a cookie and send it back to the client. However, this would mean that your application must conform to this way of token handling which is obviously opinionated. I wanted to keep things as simple as possible, so the hash fragment approach is much, much easier to implement and demonstrate.

It's important to point out that the login frontend which comes with this project is optional! You can build your own! 😃 It's the main reason I decoupled everything so the API can be deployed without the frontend. Same goes for emails. You can even integrate the API into your application so it runs on the same domain (which however is not advisable, due to a greater surface for security risks).

**Comment by squidfunk** [comment]
Can this issue be closed?

**Comment by pabloariasmora** [comment]
@squidfunk  thanks for the explanation, and sure you can close it, sorry I didn't quite get the initial idea at first, now that you gave me the explanation is easy to follow. 

Thanks
