### ISSUE TITLE
Usage with aws-amplify

### ISSUE THREAD

**Issue by trungduyvu** [squidfunk/terraform-aws-cognito-auth#344]
## Description
Not a bug. How would you use this module with [AWS-Amplify](https://aws-amplify.github.io/docs/js/authentication)

I have successfully got AWS IAM credential using cognito userpool token returned by this. However, simply putting it in AWS.config.credentials is not enough since all subsequent calls still got 403 errors.

Wonder if anyone got this working?

**Comment by squidfunk** [comment]
I haven't dug into AWS Amplify, so I cannot really answer this question. If you manage to get it suited to your needs, feel free to post your updates in this issue, so somebody else wanting to achieve the same thing has a starting point.

**Comment by squidfunk** [comment]
**tl;dr: this project is meant to be a replacement for Cognito's hosted UI and expose authentication programmatically through well-defined APIs.**

Another take on this: the main idea behind this project is to decouple authentication with AWS Cognito in a way that it can be used without the client-side `aws-sdk`. Up to now, the recommended way was to use [amazon-cognito-auth-js](https://github.com/aws/amazon-cognito-auth-js) which only allows you to use Cognito's hosted UI (which I find to be awful). From the docs:

> Instead of implementing a UI for sign-up and sign-in, this SDK provides the UI via a hosted page. It supports sign-up, sign-in, confirmation, multifactor authentication, and sign-out.

`terraform-aws-cognito-auth` was built out of this frustration, as I wanted to create a beautiful and custom UI for the SPAs I'm building instead of being limited by the very few configuration possibilities of the hosted UI. Now there's AWS Amplify, which seems to just recently have added support to [use your own UI](https://github.com/aws-amplify/amplify-js/issues/1585#issuecomment-482695713). You might want to stick to their authentication logic, if you want to use Amplify anyway. From [their docs](https://aws-amplify.github.io/docs/js/authentication#retrieve-current-session):

> Auth.currentSession() returns a CognitoUserSession object which contains JWT accessToken, idToken, and refreshToken.

This is exactly what `terraform-aws-cognito-auth` will give you. The hosted GUI manages access to the `refresh` token in a secure way and will redirect to the configured URL with the `id` token in the hash fragment. Depending on what you need, you could pass the `access` token instead, or both. As I've written in my previous message, we could make it configurable, if necessary.

Why use this project then? Well, if you're building an app that is closed source, calling AWS services directly might be fine, but when you're building an SPA whose source is open by design, you might not want to expose any AWS calls and subsequently credentials to the client. Furthermore, you don't want to increase your footprint with the bloat that is the `aws-sdk`. You want to use a JWT token to access your own APIs in a controllable and containable manner. Furthermore, you want to be sure that any code changes in your application won't introduce vulnerabilities into your authentication flow. This is the reason why the UI provided by this project is hosted under a separate domain with very strict CSPs etc. You also don't want to expose the `refresh` token to potential XSS or CSRF attacks. This is also handled. The main use case are, in fact, SPAs.

I'm closing this issue now, as I feel that this question was thoroughly answered. If you've further questions, feel free to post them here.
